source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

gem "rails", "~> 7.1"
gem "puma", "~> 6.0"
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.7"
gem "redis", "~> 5.0"
gem "rack-cors"

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "database_cleaner-active_record"
  gem "shoulda-matchers"
  gem "standard"
  gem "brakeman"
end

group :development do
  gem "listen"
  gem "byebug"
end

